klaviyo-php lib compatibility for track message time
broken-titan/laravel-klaviyo-channel pull request #4
Opened 2021-10-06 19:05 UTC by antongorodezkiy

With `string $time` this code https://github.com/klaviyo/php-klaviyo/blob/master/src/Model/EventModel.php#L49 will cause timestamp `1633546561` to be formatted to `144902122434` and metric tracking will fail with Klaviyo API response `0`. So it should be cast as integer to pass that condition

2021-10-06 19:22 UTC, antongorodezkiy commented
Alternatively we can pass time not as timestamp, but as string instead https://github.com/broken-titan/laravel-klaviyo-channel/blob/master/src/Messages/KlaviyoTrackMessage.php#L35 :

```
use DateTime;
...
$this->time = $time ? $time->format(DateTime::W3C) : null;
```

2021-10-15 23:26 UTC, th3third requested changes
Thank you for pointing this out. I like the second suggestion since that seems more readable on the object properties.

2021-10-15 23:26 UTC, th3third commented on src/Messages/KlaviyoTrackMessage.php
>  			$this->time = $time ? $time->format("U") : null;
We should be able to get the date format constant from DateTimeInterface which is already included too.

```suggestion
			$this->time = $time ? $time->format(DateTimeInterface::W3C) : null;
```

2021-10-15 23:26 UTC, th3third commented on src/Messages/KlaviyoTrackMessage.php
> +		public ?int $time;
```suggestion
		public ?string $time;
```

2021-10-15 23:26 UTC, th3third commented on src/Messages/KlaviyoTrackMessage.php
> +		public ?int $time;
Revert back to string if using DateTimeInterface::W3C.

2021-10-16 00:54 UTC, th3third approved these changes

2021-10-16 00:56 UTC, merged